import React, { useEffect, useState } from "react";
import "./App.scss";
import axios from "axios";

// import components
import Home from "./components/Home";
import Header from "./components/Header";
import NavDesktop from "./components/NavDesktop";

// import material ui
import { create } from "jss";
import rtl from "jss-rtl";
import { StylesProvider, jssPreset } from "@material-ui/core/styles";

import { createMuiTheme, ThemeProvider } from "@material-ui/core/styles";

const theme = createMuiTheme({
  direction: "rtl", // Both here and <body dir="rtl">
});

// Configure JSS
const jss = create({ plugins: [...jssPreset().plugins, rtl()] });

function App() {
  const [data, setData] = useState(false);
  const [exampleData, setExampleData] = useState([
    {
      ID: "1",
      Date: "13/07/2020",
      HOUR: "13:04:00",
      LeadSource: "כללי",
      Name: "רונן כהן",
      "Email-F": "ronen@gmail.com",
      Tel: "052-88542036",
      Age: "17",
      City: "כפר סבא",
      "Relevant-F": "TRUE",
      "Event1-F": "התקשרנו ללא מענה",
      "DateEvent1-F": "29/5/2020",
      StatusEvent1: "קנה",
      "Event2-F": "הגיע לשיעור ניסיון",
      DateEvent2: "29/5/2020",
      StatusEvent2: "קנה",
      LeadMission: "לעשות פולואו אפ",
      DateMission: "22/12/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "TRUE",
      "PurchasedAmount-F": "₪2,000.00",
      LeadRate: "8",
      LeadCost: "₪60.00",
    },
    {
      ID: "2",
      Date: "24/11/2020",
      HOUR: "13:04:00",
      LeadSource: "ליד טלפוני",
      Name: "מיכל לוי",
      "Email-F": "michal@gmail.com",
      Tel: "052-99650402",
      Age: "12",
      City: "תל אביב",
      "Relevant-F": "FALSE",
      "Event1-F": "התקשרנו ולא רלוונטי",
      "DateEvent1-F": "20/2/2021",
      StatusEvent1: "מחכה לתיאום פגישה",
      "Event2-F": "הגיע לשיעור ניסיון",
      DateEvent2: "20/2/2021",
      StatusEvent2: "מחכה לתיאום פגישה",
      LeadMission: "לעשות פולואו אפ",
      DateMission: "20/12/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "FALSE",
      "PurchasedAmount-F": "",
      LeadRate: "5",
      LeadCost: "₪100.00",
    },
    {
      ID: "3",
      Date: "24/06/2020",
      HOUR: "13:04:00",
      LeadSource: "ליד טלפוני",
      Name: "קים זינגר",
      "Email-F": "kim_zin@hotmail.com",
      Tel: "050-65893654",
      Age: "10",
      City: "ניר אליהו",
      "Relevant-F": "TRUE",
      "Event1-F": "התקשרנו ונקבע שיעור ניסיון",
      "DateEvent1-F": "2/1/2020",
      StatusEvent1: "חושב",
      "Event2-F": "הגיע לשיעור ניסיון מחכה לרישום",
      DateEvent2: "2/1/2020",
      StatusEvent2: "קנה",
      LeadMission: "לעשות פולואו אפ",
      DateMission: "18/12/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "TRUE",
      "PurchasedAmount-F": "₪369.00",
      LeadRate: "8",
      LeadCost: "₪60.00",
    },
    {
      ID: "4",
      Date: "22/11/2020",
      HOUR: "13:04:00",
      LeadSource: "דף נחיתה",
      Name: "נמרוד שטיין",
      "Email-F": "nimrod@gmail.com",
      Tel: "054-66892045",
      Age: "16",
      City: "רמת השרון",
      "Relevant-F": "TRUE",
      "Event1-F": "התקשרנו ללא מענה",
      "DateEvent1-F": "25/6/2020",
      StatusEvent1: "חושב",
      "Event2-F": "הגיע לשיעור ניסיון - לא רלוונטי",
      DateEvent2: "25/6/2020",
      StatusEvent2: "מתעניין",
      LeadMission: "הוצאת חשבונית למייל",
      DateMission: "14/12/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "FALSE",
      "PurchasedAmount-F": "",
      LeadRate: "",
      LeadCost: "₪45.00",
    },
    {
      ID: "5",
      Date: "28/08/2020",
      HOUR: "13:04:00",
      LeadSource: "כללי",
      Name: "סיגל טובים",
      "Email-F": "sigal_tov@gmail.com",
      Tel: "054-89798050",
      Age: "16",
      City: "מתן",
      "Relevant-F": "FALSE",
      "Event1-F": "התקשרנו ונקבע שיעור ניסיון",
      "DateEvent1-F": "1/1/2021",
      StatusEvent1: "מתעניין",
      "Event2-F": "הגיע לשיעור ניסיון ומעוניין בשיעור ניסיון נוסף",
      DateEvent2: "1/1/2021",
      StatusEvent2: "קנה",
      LeadMission: "קביעת פגישה חדשה",
      DateMission: "3/1/2021",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "TRUE",
      "PurchasedAmount-F": "₪3,400.00",
      LeadRate: "10",
      LeadCost: "₪240.00",
    },
    {
      ID: "6",
      Date: "27/10/2020",
      HOUR: "13:04:00",
      LeadSource: "דף נחיתה",
      Name: "לירי שמואלי",
      "Email-F": "liri@gmail.com",
      Tel: "056-99878987",
      Age: "7",
      City: "צור יגאל",
      "Relevant-F": "TRUE",
      "Event1-F": "התקשרנו ונקבע שיעור ניסיון",
      "DateEvent1-F": "9/8/2020",
      StatusEvent1: "חושב",
      "Event2-F": "הגיע לשיעור ניסיון - לא רלוונטי",
      DateEvent2: "9/8/2020",
      StatusEvent2: "מחכה לתיאום פגישה",
      LeadMission: "ביטול עסקה והחזר כספי",
      DateMission: "22/11/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "TRUE",
      "PurchasedAmount-F": "₪238.00",
      LeadRate: "7",
      LeadCost: "₪67.00",
    },
    {
      ID: "7",
      Date: "24/09/2020",
      HOUR: "13:04:00",
      LeadSource: "דף נחיתה",
      Name: "לילך זרהין",
      "Email-F": "lilach@hotmail.com",
      Tel: "052-36545477",
      Age: "11",
      City: "כפר סבא",
      "Relevant-F": "FALSE",
      "Event1-F": "התקשרנו ולא רלוונטי",
      "DateEvent1-F": "9/8/2020",
      StatusEvent1: "קנה",
      "Event2-F": "מעוניין ביצירת קשר נוספת",
      DateEvent2: "9/8/2020",
      StatusEvent2: "מתעניין",
      LeadMission: "לעשות פולואו אפ",
      DateMission: "10/12/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "FALSE",
      "PurchasedAmount-F": "",
      LeadRate: "3",
      LeadCost: "₪100.00",
    },
    {
      ID: "8",
      Date: "24/11/2020",
      HOUR: "13:04:00",
      LeadSource: "כללי",
      Name: "מיכאלה לוינסקי",
      "Email-F": "michaela@gmail.com",
      Tel: "052-88887946",
      Age: "17",
      City: "נתניה",
      "Relevant-F": "TRUE",
      "Event1-F": "התקשרנו ללא מענה",
      "DateEvent1-F": "10/10/2020",
      StatusEvent1: "מתעניין",
      "Event2-F": "הגיע לשיעור ניסיון",
      DateEvent2: "10/10/2020",
      StatusEvent2: "חושב",
      LeadMission: "הוצאת חשבונית למייל",
      DateMission: "24/11/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "TRUE",
      "PurchasedAmount-F": "₪3,466.00",
      LeadRate: "10",
      LeadCost: "₪100.00",
    },
    {
      ID: "9",
      Date: "25/10/2020",
      HOUR: "13:04:00",
      LeadSource: "ליד טלפוני",
      Name: "נירית אביטל",
      "Email-F": "nirit@gmail.com",
      Tel: "054-98976545",
      Age: "12",
      City: "כפר סבא",
      "Relevant-F": "TRUE",
      "Event1-F": "התקשרנו ולא רלוונטי",
      "DateEvent1-F": "23/12/2020",
      StatusEvent1: "קנה",
      "Event2-F": "הגיע לשיעור ניסיון מחכה לרישום",
      DateEvent2: "23/12/2020",
      StatusEvent2: "קנה",
      LeadMission: "קביעת פגישה חדשה",
      DateMission: "26/11/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "FALSE",
      "PurchasedAmount-F": "",
      LeadRate: "2",
      LeadCost: "₪130.00",
    },
    {
      ID: "10",
      Date: "24/11/2020",
      HOUR: "13:04:00",
      LeadSource: "דף נחיתה",
      Name: "ליבי שטרן",
      "Email-F": "livi_shtern@gmail.com",
      Tel: "052-99887456",
      Age: "9",
      City: "נתניה",
      "Relevant-F": "TRUE",
      "Event1-F": "התקשרנו ללא מענה",
      "DateEvent1-F": "28/9/2020",
      StatusEvent1: "קנה",
      "Event2-F": "הגיע לשיעור ניסיון - לא רלוונטי",
      DateEvent2: "28/9/2020",
      StatusEvent2: "קנה",
      LeadMission: "לעשות פולואו אפ",
      DateMission: "22/11/2020",
      MissionNote: "הערה לדוגמא",
      "Purchased-F": "TRUE",
      "PurchasedAmount-F": "₪3,287.00",
      LeadRate: "9",
      LeadCost: "₪210.00",
    },
    {
      ID: "",
      Date: "",
      HOUR: "",
      LeadSource: "",
      Name: "",
      "Email-F": "",
      Tel: "",
      Age: "",
      City: "",
      "Relevant-F": "FALSE",
      "Event1-F": "",
      "DateEvent1-F": "",
      StatusEvent1: "",
      "Event2-F": "",
      DateEvent2: "",
      StatusEvent2: "",
      LeadMission: "",
      DateMission: "",
      MissionNote: "",
      "Purchased-F": "FALSE",
      "PurchasedAmount-F": null,
      LeadRate: null,
      LeadCost: null,
    },
    {
      ID: "",
      Date: "",
      HOUR: "",
      LeadSource: "",
      Name: "",
      "Email-F": "",
      Tel: "",
      Age: "",
      City: "",
      "Relevant-F": "FALSE",
      "Event1-F": "",
      "DateEvent1-F": "",
      StatusEvent1: "",
      "Event2-F": "",
      DateEvent2: "",
      StatusEvent2: "",
      LeadMission: "",
      DateMission: "",
      MissionNote: "",
      "Purchased-F": "FALSE",
      "PurchasedAmount-F": null,
      LeadRate: null,
      LeadCost: null,
    },
    {
      ID: "",
      Date: "",
      HOUR: "",
      LeadSource: "",
      Name: "",
      "Email-F": "",
      Tel: "",
      Age: "",
      City: "",
      "Relevant-F": "FALSE",
      "Event1-F": "",
      "DateEvent1-F": "",
      StatusEvent1: "",
      "Event2-F": "",
      DateEvent2: "",
      StatusEvent2: "",
      LeadMission: "",
      DateMission: "",
      MissionNote: "",
      "Purchased-F": "FALSE",
      "PurchasedAmount-F": null,
      LeadRate: null,
      LeadCost: null,
    },
  ]);

  const getDataFromSheet = async () => {
    const dataSheet = await axios
      .get("https://sheet.best/api/sheets/6c613560-926d-4171-8892-5ba0bae57c44")
      .then((res) => {
        setData(res.data);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  // disable to save cost of request during work
  /*
  useEffect(() => {
    getDataFromSheet();
  }, []);
*/
  return (
    <StylesProvider jss={jss}>
      <div className="app" dir="rtl">
        <ThemeProvider theme={theme}>
          <Header />
          <main className="app__main">
            <NavDesktop />
            <Home data={exampleData} />
          </main>
        </ThemeProvider>
      </div>
    </StylesProvider>
  );
}

export default App;
